first commit
mate-academy/react_static-list-of-todos pull request #1067
Opened 2022-07-21 14:00 UTC by pavel-gutsal

https://pavel-gutsal.github.io/react_static-list-of-todos/

2022-07-22 11:15 UTC, valerii-derkach requested changes

2022-07-22 11:15 UTC, valerii-derkach commented on src/components/TodoInfo/TodoInfo.tsx
> +  </article>
render user only if it is exists

2022-07-22 12:41 UTC, pavel-gutsal commented
user will be rendered only if  property value is truish

2022-07-26 10:04 UTC, Bohdan-Maksymiuk approved these changes
Good job 👍

2022-07-26 10:04 UTC, Bohdan-Maksymiuk commented on src/components/TodoInfo/TodoInfo.tsx
> +    )}
use `classnames` library for conditional classes
https://www.npmjs.com/package/classnames

2022-07-26 10:04 UTC, Bohdan-Maksymiuk commented on src/components/TodoInfo/TodoInfo.tsx
> +    { todo?.user && (<UserInfo user={todo.user} />)}
```suggestion
    {todo?.user && <UserInfo user={todo.user} />}
```
or if component is big
```
  {todo?.user && (
    <UserInfo user={todo.user} />
  )}
```

2022-07-26 10:05 UTC, alexandra-protyanova approved these changes

2022-10-07 11:37 UTC, closed without merging