Solution
mate-academy/react_static-list-of-todos pull request #1186
Opened 2022-09-08 16:35 UTC by vladgusakovskiy

[DEMO LINK](https://vladgusakovskiy.github.io/react_static-list-of-todos/)

2022-09-09 08:40 UTC, OleksiiPustovit approved these changes
Good job 🔥

2022-09-09 09:24 UTC, AndriiRut requested changes

2022-09-09 09:24 UTC, AndriiRut commented on src/components/TodoInfo/TodoInfo.tsx
> +    >
instal classnames module and use it in classNames

2022-09-12 07:46 UTC, denys-danyliuk commented on src/components/TodoInfo/TodoInfo.tsx
> +      {user ? <UserInfo user={user} /> : null}
let's write some message instead of a null, something like 'There is no user'

2022-09-12 07:47 UTC, denys-danyliuk approved these changes
GJ!

2024-01-15 19:58 UTC, closed without merging