task solution
mate-academy/react_static-list-of-todos pull request #1248
Opened 2022-10-12 15:05 UTC by vladyslav-harkusha

[DEMO LINK](https://vladyslav-harkusha.github.io/react_static-list-of-todos/)

2022-10-13 10:18 UTC, imaksweb approved these changes
Nice work 🔥

2022-10-13 14:08 UTC, Denchepornyuk requested changes

2022-10-13 14:08 UTC, Denchepornyuk commented on src/components/UserInfo/UserInfo.tsx
> +  </a>
it's better to not render `a` if user is `null`

2022-10-17 10:04 UTC, OleksiiBlezniuk requested changes

2022-10-17 10:04 UTC, OleksiiBlezniuk commented on src/components/TodoList/TodoList.tsx
> +  </section>
Use semantic tags for list and its items

2022-10-17 10:57 UTC, vladyslav-harkusha commented on src/components/TodoList/TodoList.tsx
> +  </section>
But in the task, we only have to split the given markup into components, and don't change class names

2022-10-17 11:59 UTC, OleksiiBlezniuk commented on src/components/TodoList/TodoList.tsx
> +  </section>
Okay, probably it's not so strong option, but still using of semantic tags is better then not using of them, tags is not a classes, using of `ul` and `li` tags wouldn't break your layout or tests (in this case)

2022-10-17 11:59 UTC, OleksiiBlezniuk approved these changes

2024-10-30 19:06 UTC, closed without merging