Solution
mate-academy/react_static-list-of-todos pull request #1337
Opened 2022-11-16 18:07 UTC by Andriy-Shymkiv

[DEMO LINK](https://andriy-shymkiv.github.io/react_static-list-of-todos/)

2022-11-16 22:01 UTC, Anna-Shapovalova approved these changes
GJ! 👍 Left some comments)

2022-11-17 09:41 UTC, illiarerun requested changes

2022-11-17 09:41 UTC, illiarerun commented on src/components/TodoInfo/TodoInfo.tsx
> +    >
agree, fix it

2022-11-17 09:41 UTC, illiarerun commented on src/components/TodoList/TodoList.tsx
> +  todo: Array<Todo>;
agree

2022-11-17 09:41 UTC, illiarerun commented on src/components/TodoList/TodoList.tsx
> +    {todo.map(item => (
agree

2022-11-17 09:41 UTC, illiarerun commented on src/components/TodoList/TodoList.tsx
> +      </>
agree

2022-11-21 16:48 UTC, denys-danyliuk approved these changes

2024-03-27 08:40 UTC, closed without merging