added solution
mate-academy/react_static-list-of-todos pull request #1364
Opened 2022-11-18 17:52 UTC by kryvets-vadym

[DEMO LINK](https://kryvets-vadym.github.io/react_static-list-of-todos/)

2022-11-22 10:15 UTC, bohdan-stepanets approved these changes
Good job but read please comments in TodoInfo.tsx and TodoList.tsx

2022-11-22 10:15 UTC, bohdan-stepanets commented on src/components/TodoList/TodoList.tsx
> +        return (
No need in return if it is Arrow function

2022-11-22 10:15 UTC, bohdan-stepanets commented on src/components/TodoInfo/TodoInfo.tsx
> +  const { user } = todo;
You make double `{ smth } = todo`

2022-11-22 10:15 UTC, bohdan-stepanets commented on src/components/TodoInfo/TodoInfo.tsx
> +import React from 'react';
Will be cool if you move some css properties from main App.scss to Smth.scss

2022-11-22 11:25 UTC, Olexandr6 commented on src/components/TodoInfo/TodoInfo.tsx
> +import React from 'react';
+1

2022-11-22 11:25 UTC, Olexandr6 commented on src/components/TodoList/TodoList.tsx
> +        return (
+1

2022-11-22 11:26 UTC, Olexandr6 requested changes
Fix comments that you colleague mentioned above

2022-11-22 11:27 UTC, Olexandr6 commented on src/components/TodoInfo/TodoInfo.tsx
> +import React from 'react';
Let's move styles from App.scss to separate files as well

2022-11-23 13:56 UTC, Olexandr6 approved these changes
Good job 👍

2024-01-15 14:08 UTC, closed without merging