solution
mate-academy/react_static-list-of-todos pull request #1505
Opened 2023-01-20 16:05 UTC by igor-kashchenko

[DEMO LINK](https://igor-kashchenko.github.io/react_static-list-of-todos/)

2023-01-22 20:07 UTC, OlhaYevstifieieva approved these changes
Nice Job!

2023-01-24 09:38 UTC, Denchepornyuk requested changes

2023-01-24 09:38 UTC, Denchepornyuk commented on src/components/TodoList/TodoList.tsx
> +    ))}
where is `key` attribute?

2023-01-24 11:43 UTC, Denchepornyuk approved these changes

2024-11-08 14:13 UTC, closed without merging