Solution react_static-list-of-todos
mate-academy/react_static-list-of-todos pull request #1717
Opened 2023-04-07 16:55 UTC by NazariiAlieksieiev

[DEMO LINK](https://NazariiAlieksieiev.github.io/react_static-list-of-todos/)

2023-04-07 17:33 UTC, loralevitska requested changes
Almost perfect) Let's improve

2023-04-07 17:33 UTC, loralevitska commented on src/components/TodoInfo/TodoInfo.tsx
> +export const TodoInfo: React.FC<Props> = ({ todo }) => (
Destructure `todo`

2023-04-07 17:33 UTC, loralevitska commented on src/components/TodoList/TodoList.tsx
> +  <>
Remove redundant react fragment. https://blog.logrocket.com/understanding-react-fragments/

2023-04-07 17:33 UTC, loralevitska commented on src/components/TodoList/TodoList.tsx
> +    </section>
Use semantic tags for list `ul` `li`. Don't forget to remove default `li` dots

2023-04-07 17:33 UTC, loralevitska commented on src/components/UserInfo/UserInfo.tsx
> +  </>
You check user in TodoInfo
After that check, he will always be here
And destructure `user`
```suggestion
  <a
          key={user.id}
          className="UserInfo"
          href={`mailto:${user.email}`}
        >
          {user.name}
        </a>
```

2023-04-07 17:33 UTC, loralevitska commented on src/components/TodoInfo/TodoInfo.tsx
> +        )}
```suggestion
      {todo.user && <UserInfo user={todo.user} />}
```

2023-04-09 08:01 UTC, etojeDenys requested changes

2023-04-09 08:01 UTC, etojeDenys commented on src/components/TodoInfo/TodoInfo.tsx
> +    <>
also remove this redundant fragment

2023-04-09 08:01 UTC, etojeDenys commented on src/components/UserInfo/UserInfo.tsx
> +    <>
redundant fragment

2023-04-09 12:11 UTC, VitaliyBondarenko1982 approved these changes

2024-07-27 11:08 UTC, closed without merging