Add React Static List of TODOs
mate-academy/react_static-list-of-todos pull request #1832
Opened 2023-05-22 15:43 UTC by ruslanpashkov

[DEMO LINK](https://ruslanpashkov.github.io/react_static-list-of-todos/)

2023-05-22 18:59 UTC, DidenkoDenis306 approved these changes

2023-05-24 08:25 UTC, 33Orange requested changes
Good job. 

Just a one moment to fix

2023-05-24 08:25 UTC, 33Orange commented on src/components/TodoInfo/TodoInfo.tsx
> +    <article className={`TodoInfo ${completed && 'TodoInfo--completed'}`}>
`completed && 'TodoInfo--completed'` this condition will be add 'false' as className if `completed === false
`

Try something else. 

<img width="431" alt="image" src="https://github.com/mate-academy/react_static-list-of-todos/assets/84296041/ca162933-e6dc-4159-b71f-f482a9c4ace9">

2023-05-25 07:14 UTC, 33Orange approved these changes
Good job

2023-05-25 07:14 UTC, 33Orange commented on src/components/TodoInfo/TodoInfo.tsx
> +    >
Okay, it's interesting solution.
But to use a whole external library in order to insert 1 style ? :)
```suggestion
    <article className={`TodoInfo ${completed ? 'TodoInfo--completed' : ''}`} >
```

2023-12-12 12:56 UTC, closed without merging