Develop
mate-academy/react_static-list-of-todos pull request #394
Opened 2021-02-13 18:51 UTC by b0hdan1

2021-02-15 10:01 UTC, vkryvytskyy requested changes
![зображення](https://user-images.githubusercontent.com/38065883/107931623-35454e00-6f85-11eb-8397-df8f9e8271ec.png)
Добавить немного стилей не помешало бы

2021-02-15 10:01 UTC, vkryvytskyy commented on src/components/Todo.js
> +        <p>{completed ? 'true' : 'false'}</p>
```suggestion
        <p>{completed ? 'Completed' : 'In progress'}</p>
```
Что `true`? Что `false`?

2021-02-15 10:01 UTC, vkryvytskyy commented on src/components/TodoList.js
> +          {/* {console.log(todo, todo.id)} */}
Удаляй логи

2021-02-15 10:01 UTC, vkryvytskyy commented on src/components/TodoList.js
> +import Todo from './Todo';
Используй named exports, вместо default

2021-02-17 08:53 UTC, vpolets approved these changes

2021-02-17 08:53 UTC, vpolets commented on src/App.js
> +    user: users.find(el => el.id === todo.userId),
Чому не вніс правки? Давай називати змінні правильно

2024-04-25 17:23 UTC, closed without merging