Solution
mate-academy/react_static-list-of-todos pull request #461
Opened 2021-05-17 17:39 UTC by igor-stasiv

[DEMO LINK](https://igor-stasiv.github.io/react_static-list-of-todos/)

2021-05-18 10:52 UTC, Burunduk003 approved these changes
Good job! You can do some little fixes that I mention.

2021-05-18 10:52 UTC, Burunduk003 commented on src/App.js
> +
Это все можно сделать за раз через мап. Можешь глянуть мое решение. Я раньше тоже где можно юзал форИч но меня Миша уже почти отучил)))

2021-05-18 10:52 UTC, Burunduk003 commented on src/components/Todo/Todo.jsx
> +    }),
Ты тут нигде не используешь id, так почему он у тебя тут обязателен? Я еще понимаю name, так как ты его передаешь в компонент юзер (хоть и вместе с целым объектом). Я написал name, хотя по хорошему тут можно ограничится проверкой на объект и все.

2021-05-19 04:43 UTC, VinnieJ-2k20 requested changes
Good solution, just need to make some small edits.

2021-05-19 04:43 UTC, VinnieJ-2k20 commented on src/components/Todo/Todo.jsx
> +  }).isRequired,
You don't use `user.name` in this component, so there's no need to validate it here. Just check if user is an object.

2021-05-19 04:43 UTC, VinnieJ-2k20 commented on src/components/Todo/Todo.jsx
> +  completed: PropTypes.bool,
Better make it required.

2021-05-19 10:02 UTC, VinnieJ-2k20 approved these changes
Good job 👍

2021-05-19 10:02 UTC, VinnieJ-2k20 commented on src/components/Todo/Todo.jsx
> +  user: PropTypes.object.isRequired,
Should work like this without disabling linter:
```suggestion
  user: PropTypes.shape({}).isRequired,
```

2021-05-19 10:12 UTC, igor-stasiv commented on src/components/Todo/Todo.jsx
> +  user: PropTypes.object.isRequired,
Ok, I will keep this in mind

2024-12-15 15:27 UTC, closed without merging