Solution
mate-academy/react_static-list-of-todos pull request #500
Opened 2021-05-19 21:58 UTC by ivan-shpynda

[DEMO LINK](https://ivan-shpynda.github.io/react_static-list-of-todos/)

2021-05-20 10:17 UTC, Grygoriy-Shytikov approved these changes
Виглядає добре! 👍

2021-05-20 10:17 UTC, Grygoriy-Shytikov commented on src/components/ToDo.jsx
> +};
Думаю тут можна розрити код - щоб легше читалось

```
const typeUser = PropTypes.shape({
  name: PropTypes.string.isRequired,
});

Todo.propTypes = {
  id: PropTypes.number.isRequired,
  title: PropTypes.string.isRequired,
  user: typeUser.isRequired,
  completed: PropTypes.bool.isRequired,
};
```

2021-05-20 12:21 UTC, aliceblunt8 requested changes

2021-05-20 12:21 UTC, aliceblunt8 commented on src/App.js
> +));
```suggestion
const preparedTodos = todos.map(task => ({
    ...task,
    user: users.find(user => user.id === task.userId),
  }));
```

2021-05-20 12:21 UTC, aliceblunt8 commented on src/App.js
> +      <TodoList preparedTodos={preparedTodos} />
```suggestion
      <TodoList todos={preparedTodos} />
```

2021-05-20 12:21 UTC, aliceblunt8 commented on src/components/ToDo.jsx
> +    isCompleted = 'is NOT completed';
remove this unnecessary logic, use ternary operator inside className and jsx

2021-05-20 12:21 UTC, aliceblunt8 commented on src/components/TodoList.jsx
> +  return (
```suggestion
export const TodoList = ({ todos }) => (
```

2021-05-20 12:21 UTC, aliceblunt8 commented on src/components/TodoList.jsx
> +      <div>
remove this div, it's redundant here

2021-05-20 13:36 UTC, ivan-shpynda commented on src/components/ToDo.jsx
> +};
дякую, справді трохи зрозуміліше

2021-05-21 13:43 UTC, VinnieJ-2k20 approved these changes

2024-09-13 09:51 UTC, closed without merging