Solution?
mate-academy/react_static-list-of-todos pull request #564
Opened 2021-07-20 09:35 UTC by Vivdyuk

[DEMO LINK](https://vivdyuk.github.io/react_static-list-of-todos/)

2021-07-20 10:14 UTC, NYaremchuk approved these changes

2021-07-20 14:28 UTC, ArtemTopolskyi requested changes
Мне, как трипофобу, дизайн не понравился

2021-07-20 14:28 UTC, ArtemTopolskyi commented on src/components/Todo/Todo.jsx
> +  user: PropTypes.shape().isRequired,
опиши полностью тип

2021-07-20 14:28 UTC, ArtemTopolskyi commented on src/components/Todo/Todo.jsx
> +      {`${completed ? `done` : `in progress`}`}
используй template string, {' '} не ок

2021-07-20 14:28 UTC, ArtemTopolskyi commented on src/components/TodoList/TodoList.jsx
> +  todos: PropTypes.arrayOf().isRequired,
arrayOf what? опиши тип тудушек

2021-07-21 07:57 UTC, ArtemTopolskyi requested changes

2021-07-21 07:57 UTC, ArtemTopolskyi commented on src/App.js
> +import './components/TodoList/TodoList.scss';
эти импорты должны быть в соответствующих компонентах

2021-07-21 07:57 UTC, ArtemTopolskyi commented on src/components/Todo/Todo.jsx
> +  }).isRequired,
Лучше передавать объект юзера целиком в компонент User. Соответственно и propTypes нужно описывать для всех полей юзера, а не только для имени.

2021-07-21 07:57 UTC, ArtemTopolskyi commented on src/components/Todo/Todo.jsx
> +      {user}
{' '} не ок

2021-07-21 11:07 UTC, ArtemTopolskyi approved these changes

2021-07-21 11:07 UTC, ArtemTopolskyi commented on src/components/TodoList/TodoList.jsx
> +          user={todo.user}
почему бы просто не передать объект todo, зачем три разных пропсы

2021-07-21 11:07 UTC, ArtemTopolskyi commented on src/components/TodoList/TodoList.jsx
> +    }),
в компонент TodoList приходит массив todos, опиши полностью массив todos, а не только имя

2023-02-13 12:05 UTC, closed without merging