taras holiuk's solution
mate-academy/react_static-list-of-todos pull request #595
Opened 2021-08-31 16:55 UTC by TarasHoliuk

[DEMO LINK](https://tarasholiuk.github.io/react_static-list-of-todos/)

2021-09-01 13:30 UTC, alex-glotov67 commented on src/components/TodoList/TodoList.tsx
> +      })}
Тут якщо `user`  в нас `null` всі решту данних ми маємо виводити окрім даних юзера

2021-09-01 13:32 UTC, alex-glotov67 commented on src/types/types.tsx
> +export interface User {
Тобі дійсно потрібні всі ці властивості в інтерфейсі? Пропиши лише ті якими будеш користуватись.

2021-09-01 15:03 UTC, TarasHoliuk commented on src/types/types.tsx
> +export interface User {
Так, таки не потрібні
Ідея була прописати тип об'єкту який приходить, але мабуть тут це таки зайве

2021-09-01 15:04 UTC, TarasHoliuk commented on src/components/TodoList/TodoList.tsx
> +      })}
👍

2021-09-01 15:06 UTC, TarasHoliuk commented on src/App.tsx
> +});
Have no idea)

2021-09-02 14:00 UTC, danheim requested changes

2021-09-02 14:00 UTC, danheim commented on src/App.tsx
> +    <TodoList todosArray={preparedTodos} />
avoid array word

2021-09-02 14:01 UTC, danheim requested changes

2021-09-03 09:26 UTC, Denchepornyuk approved these changes

2023-10-15 09:32 UTC, closed without merging