Develop
mate-academy/react_static-list-of-todos pull request #61
Opened 2019-09-09 06:32 UTC by aleks-and

[DEMO LINK](https://aleks-and.github.io/react_static-list-of-todos/)

2019-09-09 08:56 UTC, danheim requested changes

2019-09-09 08:56 UTC, danheim commented on src/App.js
> +  ));
```suggestion
return todos.map(todo => ({
      ...todo,
      user: users.find(user => user.id === todo.userId),
    }));
```

2019-09-09 08:56 UTC, danheim commented on src/App.js
> +      </div>
Вынеси этот хедер в отдельный компонент

2019-09-09 10:30 UTC, aleks-and commented on src/App.js
> +  ));
Done!

2019-09-09 10:31 UTC, aleks-and commented on src/App.js
> +      </div>
Done!

2019-09-09 11:14 UTC, YuriiHoliuk commented on src/components/User/User.js
> +    <>
unneeded

2019-09-09 11:15 UTC, YuriiHoliuk commented on src/components/TodoList/TodoList.js
> +        {props.todos.map(todo => (
destruct

2019-09-09 11:18 UTC, YuriiHoliuk commented on src/components/TodoItem/TodoItem.js
> +function TodoItem({todo}) {
- will be better to name props "props"
- better to destruct props

2019-09-09 12:18 UTC, danheim commented
new comments from Yura have not been fixed

2019-09-09 12:41 UTC, aleks-and commented on src/components/User/User.js
> +    <>
Fixed!

2019-09-09 12:42 UTC, aleks-and commented on src/components/TodoList/TodoList.js
> +        {props.todos.map(todo => (
Fixed?

2019-09-09 12:42 UTC, aleks-and commented on src/components/TodoItem/TodoItem.js
> +function TodoItem({todo}) {
Fixed!

2019-09-09 14:05 UTC, danheim requested changes

2019-09-09 14:05 UTC, danheim commented on src/components/Header/Header.js
> +  return (
давай возвращать сразу jsx без return
```
const Header = ({ userCount, todosCount }) => (
  <div>
    ..content
  </div>
)
```

2019-09-09 14:05 UTC, danheim commented on src/components/TodoItem/TodoItem.js
> +      <div className={`todo-list__item ${completed ? 'todo-list__item--is-complete' : ''}`}>
вынеси это в переменную, читаемость сейчас очень страдает

2019-09-09 14:05 UTC, danheim commented on src/components/TodoList/TodoList.js
> +  const { todos } = props;
делай дуструктуризацию в аргументах функции

2019-09-09 14:05 UTC, danheim commented on src/components/TodoList/TodoList.js
> +  return (
давай будем возвращать сразу `JSX`, без return, как выше написал

2019-09-09 14:05 UTC, danheim commented on src/components/User/User.js
> +function User({user}) {
```suggestion
function User({ user }) {
```

2019-09-09 14:05 UTC, danheim commented on src/components/User/User.js
> +  return (
возвращаем сразу JSX

2019-09-09 19:01 UTC, aleks-and commented on src/components/Header/Header.js
> +  return (
Fixed!

2019-09-09 19:01 UTC, aleks-and commented on src/components/TodoItem/TodoItem.js
> +      <div className={`todo-list__item ${completed ? 'todo-list__item--is-complete' : ''}`}>
Fixed!

2019-09-09 19:01 UTC, aleks-and commented on src/components/TodoList/TodoList.js
> +  const { todos } = props;
Fixed!

2019-09-09 19:01 UTC, aleks-and commented on src/components/TodoList/TodoList.js
> +  return (
Fixed!

2019-09-09 19:01 UTC, aleks-and commented on src/components/User/User.js
> +function User({user}) {
Fixed!

2019-09-09 19:01 UTC, aleks-and commented on src/components/User/User.js
> +  return (
Fixed!

2019-09-10 06:57 UTC, irenhh requested changes
https://prnt.sc/p43t79 the indentation above todos has to be bigger than the one above users

2019-09-10 06:57 UTC, irenhh commented on src/components/TodoItem/TodoItem.js
> +  const isComplete = completed ? 'todo-list__item--is-complete' : '';
`isCompleted`

2019-09-10 06:57 UTC, irenhh commented on src/components/TodoItem/TodoItem.js
> +  const isComplete = completed ? 'todo-list__item--is-complete' : '';
the same comment for className

2019-09-10 06:57 UTC, irenhh commented on src/components/User/User.js
> +      <p>User: {user.name}</p>
something wrong with the indentations here

2019-09-10 13:01 UTC, aleks-and commented on src/components/TodoItem/TodoItem.js
> +  const isComplete = completed ? 'todo-list__item--is-complete' : '';
Fixed!

2019-09-10 13:02 UTC, aleks-and commented on src/components/User/User.js
> +      <p>User: {user.name}</p>
Fixed!

2019-09-10 13:02 UTC, aleks-and commented
> https://prnt.sc/p43t79 the indentation above todos has to be bigger than the one above users

Fixed!

2019-09-10 13:58 UTC, irenhh approved these changes

2019-09-10 13:58 UTC, irenhh commented on src/components/User/User.js
> +export default User;
new line in the end of the file

2026-01-17 14:35 UTC, closed without merging