solution
mate-academy/react_static-list-of-todos pull request #635
Opened 2021-10-03 09:10 UTC by Dinexpod

[DEMO LINK](https://Dinexpod.github.io/react_static-list-of-todos/)

2021-10-04 18:59 UTC, varseniuk requested changes

2021-10-04 18:59 UTC, varseniuk commented on src/App.tsx
> +    user: (user !== undefined) ? user : null,
```suggestion
  const user = users.find(todoUser => todo.userId === todoUser.id) || null;

  return {
    user,
```

2021-10-04 18:59 UTC, varseniuk commented on src/components/TodoInfo.tsx
> +  title: string
в тебе є тип PreparedTodo, використовуй його

2021-10-04 18:59 UTC, varseniuk commented on src/components/TodoList/TodoList.tsx
> +      <tr>
Атрибут key?

2021-10-09 09:56 UTC, Dinexpod commented on src/components/TodoList/TodoList.tsx
> +      <tr>
ок

2021-10-09 10:01 UTC, Dinexpod commented on src/App.tsx
> +    user: (user !== undefined) ? user : null,
типу в самому об'єкті краще логіку не навішувати?

2021-10-11 11:28 UTC, vkryvytskyi requested changes

2021-10-11 11:28 UTC, vkryvytskyy commented on src/components/TodoList/TodoList.tsx
> +      <tr>
Ты опять просто переименовал название ключа
```suggestion
      <tr key={todo.id}>
```

2021-10-16 19:22 UTC, Dinexpod commented on src/components/TodoList/TodoList.tsx
> +      <tr>
уга, уже догнал с совета в другой задачи))

2021-10-18 08:55 UTC, danylo-onishchuk approved these changes

2026-05-10 22:08 UTC, closed without merging