Task was solved
mate-academy/react_static-list-of-todos pull request #692
Opened 2021-11-04 13:29 UTC by cyb1ove

[DEMO LINK](https://cyb1ove.github.io/react_static-list-of-todos/)

2021-11-05 09:03 UTC, Olexandr6 requested changes
In generall great work👍 But fix some things👇

2021-11-05 09:55 UTC, cyb1ove commented on src/App.tsx
> +  };
Thanks for the suggestion!

2021-11-11 10:43 UTC, solaryasha requested changes

2021-11-11 10:43 UTC, solaryasha commented on src/App.tsx
> +    <Todolist preparedTodos={preparedTodos} />
```suggestion
    <Todolist todos={preparedTodos} />
```

2021-11-11 10:43 UTC, solaryasha commented on src/components/TodoInfo/TodoInfo.tsx
> +      {user && <UserInfo {...user} />}
Потрібно явно передавати пропси

2021-11-11 10:43 UTC, solaryasha commented on src/components/Todolist/Todolist.tsx
> +          <TodoInfo {...todo} />
Потрібно явно передавати пропси

2021-11-11 11:10 UTC, solaryasha approved these changes

2025-01-20 16:30 UTC, closed without merging