Develop
mate-academy/react_static-list-of-todos pull request #725
Opened 2021-12-06 15:12 UTC by dariia-romanova

[DEMO LINK](https://dariia-romanova.github.io/react_static-list-of-todos/)

2021-12-06 16:48 UTC, Vitaliy-0 approved these changes
Good job 💯

2021-12-06 16:48 UTC, Vitaliy-0 commented on src/App.scss
> +  background-color: #ecedf1;
Use variable for color.

2021-12-06 16:48 UTC, Vitaliy-0 commented on src/components/TodoList/TodoList.tsx
> +          }
```suggestion
          {
            todo.user && <UserInfo user={todo.user} />
          }
```

2021-12-06 16:48 UTC, Vitaliy-0 commented on src/components/TodoList/TodoList.tsx
> +          }
U can write less

2021-12-06 16:48 UTC, Vitaliy-0 commented on src/components/UserInfo/UserInfo.scss
> +  gap: 30px;
Be careful with gap :)

2021-12-06 17:52 UTC, illiarerun requested changes
Good job 🔥 Let's work on fixes now:

2021-12-06 17:52 UTC, illiarerun commented on src/components/TodoList/TodoList.tsx
> +          }
Aggre with Vitaliy on this one

2021-12-06 17:52 UTC, illiarerun commented on src/components/TodoInfo/TodoInfo.tsx
> +      )}
So this divs are almost the same, only classes and inner text are different. So you can use classNames library for setting your --completed modifier and move your ternary inside just to set text, or better move it to variable

2021-12-07 14:05 UTC, illiarerun approved these changes
Great job 🔥

2023-11-19 16:07 UTC, closed without merging