Cypress tests added
mate-academy/react_static-list-of-todos pull request #891
Opened 2022-04-29 11:08 UTC by djtyrf312

2022-05-06 13:28 UTC, YevhS commented on src/components/UserInfo/UserInfo.spec.jsx
> +  it('should have a correct email', () => {
порожній рядок між тестами

2022-05-06 14:09 UTC, iBrianWarner requested changes

2022-05-06 14:09 UTC, iBrianWarner commented on README.md
> +Todo `title` should have attribute `data-cy="title"`
```suggestion
- Todo `title` should have attribute `data-cy="title"`
```
якщо не робити як пункти або не додавати два пробіла в кіні - буде як один рядок відображатися на гітхабі

2022-05-06 14:09 UTC, iBrianWarner commented on src/components/TodoInfo/TodoInfo.spec.jsx
> +    cy.get('h1').should('have.text', todos[0].title);
```suggestion
    cy.get('h1')
      .should('have.text', todos[0].title);
```

2022-05-06 14:09 UTC, iBrianWarner commented on src/components/TodoInfo/TodoInfo.spec.jsx
> +    cy.get('p').should('have.text', 'Not completed!');
```suggestion
    cy.get('p')
      .should('have.text', 'Not completed!');
```

2022-05-06 14:09 UTC, iBrianWarner commented on src/components/TodoList/TodoList.spec.jsx
> +    cy.get('li').should('have.length', todos.length);
```suggestion
    cy.get('li')
      .should('have.length', todos.length);
```

2022-05-11 15:17 UTC, iBrianWarner approved these changes

2022-05-16 12:42 UTC, oablokhina approved these changes

2022-05-23 07:36 UTC, merged