solution
mate-academy/react_static-list-of-todos pull request #948
Opened 2022-05-28 16:59 UTC by ZUBOV-ILLIA

[DEMO LINK](https://ZUBOV-ILLIA.github.io/react_static-list-of-todos/)

2022-05-28 17:27 UTC, vlad-demchuk approved these changes

2022-05-30 18:54 UTC, Anna-Tkachenko requested changes
Just check some types naming

2022-05-30 18:54 UTC, Anna-Tkachenko commented on src/App.tsx
> +  return todo.map((el: Todos) => ({
```suggestion
  return todos.map((todo: Todo) => ({
```

2022-05-30 18:54 UTC, Anna-Tkachenko commented on src/components/TodoInfo/TodoInfo.tsx
> +  obj: Todo;
What is obj?

2022-05-30 18:54 UTC, Anna-Tkachenko commented on src/react-app-env.d.ts
> +export interface Todos {
```suggestion
export interface Todo {
```

2022-05-30 18:54 UTC, Anna-Tkachenko commented on src/react-app-env.d.ts
> +export interface Todo extends Todos {
```suggestion
export interface PreparedTodo extends Todo {
```

2022-05-31 16:18 UTC, Anna-Tkachenko approved these changes
Pay attention to variable names

2022-05-31 16:18 UTC, Anna-Tkachenko commented on src/App.scss
> +// }
Delete redundant styles

2022-05-31 16:18 UTC, Anna-Tkachenko commented on src/App.tsx
> +import todo from './api/todos';
```suggestion
import todos from './api/todos';
```

2022-05-31 16:18 UTC, Anna-Tkachenko commented on src/App.tsx
> +  return todos.map((todoEl: Todo) => ({
```suggestion
  return todos.map((todo: Todo) => ({
```

2022-05-31 16:18 UTC, Anna-Tkachenko commented on src/components/TodoInfo/TodoInfo.tsx
> +  object: PreparedTodo;
What is object?

2022-05-31 16:18 UTC, Anna-Tkachenko commented on src/components/TodoInfo/TodoInfo.tsx
> +    {object.user && (<UserInfo object={object.user} />)}
```suggestion
    {object.user && (
      <UserInfo object={object.user} />
    )}
```

2025-03-11 09:25 UTC, closed without merging