Develop
mate-academy/react_static-list-of-todos pull request #981
Opened 2022-06-03 11:18 UTC by PRO-GRAM-MER

[DEMO LINK](https://PRO-GRAM-MER>.github.io/react_static-list-of-todos/)

2022-06-06 11:04 UTC, efdalyalcin approved these changes
It looks clean 👍

2022-06-07 06:46 UTC, meforoma requested changes

2022-06-07 06:46 UTC, meforoma commented on src/components/TodoInfo/TodoInfo.tsx
> +        }
here you could one-line
```suggestion
        {user && <UserInfo user={user} />}
```

2022-06-07 06:46 UTC, meforoma commented on src/components/TodoList/TodoList.tsx
> +        return (
use implicit returns when possible
```suggestion
export const TodoList: FC<Props> = ({ preparedTodos }) => (
    <ul className="todo-list">
      {preparedTodos.map(todo => (
```

2022-06-07 06:46 UTC, meforoma commented on src/react-app-env.d.ts
> +  };
for this particular task it's fine, 
but imagine that you'd need to work with Company as a standalone instance - you'd need a type / interface for it
so advise is to introduce interfaces for any nested types:
```suggestion
  company: Company;
  
 interface Company {
    name: string;
    catchPhrase: string;
    bs: string;
  };
```

2022-06-07 06:46 UTC, meforoma commented on src/react-app-env.d.ts
> +  address: {
make an interface for Address and use it here

2022-06-07 14:40 UTC, meforoma approved these changes

2026-03-29 20:35 UTC, closed without merging